var app = angular.module('myApp',[]);
var data = [{no:1,
			question:'who is the president of USA',
			subject :'current-affairs',
			answer : 'Donald Trump',
			options:[{name :'Donald Trump',
			color:'#007bff'},
			{name :'Hilary Cilton',
			color:'#007bff'},
			{name :'Barack Obama',
			color:'#007bff'},
			{name :'Mike Pence',
			color:'#007bff'}],
			choosen:''},
			{no:2,
			question:'Smallest state in Nigeria according to land mass',
			subject :'current-affairs',
			answer : 'Lagos',
			options:[{name :'Oyo',
			color:'#007bff'},
			{name :'Imo',
			color:'#007bff'},
			{name :'Lagos',
			color:'#007bff'},
			{name :'Sokoto',
			color:'#007bff'}],
			choosen:''},
			{no:3,
			question:'Hurincane Irma hits which US state in 2017',
			subject :'current-affairs',
			answer : 'Florida',
			options:[{name :'Wiscousin',
			color:'#007bff'},
			{name :'Texas',
			color:'#007bff'},
			{name :'Florida',
			color:'#007bff'},
			{name :'Alaska',
			color:'#007bff'}],
			choosen:''},
			{no:4,
			question:'How many moles of oxygen is needed to react with six moles of hydrogen when forming water',
			subject :'Chemistry',
			answer : '3',
			options:[{name :'2',
			color:'#007bff'},
			{name :'4',
			color:'#007bff'},
			{name :'6',
			color:'#007bff'},
			{name :'3',
			color:'#007bff'}],
			choosen:''},
			{no:5,
			question:'The capital city of Bangladesh is ...',
			subject :'Geography',
			answer : 'Dhaka',
			options:[{name :'Nassau',
			color:'#007bff'},
			{name :'Dhaka',
			color:'#007bff'},
			{name :'Vienna',
			color:'#007bff'},
			{name :'Minsk',
			color:'#007bff'}],
			choosen:''}];

